name: publish-page-updates
on:
  push:
    branches:
      - main
jobs:
  publish-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: src/
